version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.7-node-browsers
        environment:
          BUNDLER_VERSION: 2.1.4
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          # PGUSER: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    working_directory: ~/FitNotes
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: |
            gem install bundler -v 2.1.4
            bundle -v
      - ruby/bundle-install
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      # - run:
      #     name: Yarn のインストール
      #     command: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      # Rubocop
      # - run:
      #     name: Rubocop
      #     command: bundle exec rubocop
      # - run: bundle exec rake db:create
      # - run: bundle exec rake db:schema:load
      - run:
          name: DB の待機
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 2m

      - run:
          name: データベースのセットアップ
          command: bin/rails db:schema:load --trace

      - run:
          name: Rspec
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test_results
